### ISSUE TITLE
"value out-of-bounds" error shows if repay amount is -1

### ISSUE THREAD

**Issue by liran319** [aave/aave-js#207]
```
repay payload is below:
const payload = [
  "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",   // UNI
  -1,                                                                                              // amount
  2,                                                                                               // rateMode is variable
  "0x8F3A94725a7686055D1aaBa8a41be506c5dfD079",   //  msg.sender
]

await lendingPool.repay(...payload)
```

And error occured:
`Uncaught (in promise) Error: value out-of-bounds (argument="amount", value=-1, code=INVALID_ARGUMENT, version=abi/5.3.1)`

What's the problem here?

**Comment by sendra** [comment]
The repay method is expecting an object, and you are passing params instead. 
You should pass the info this way:
```
{
  user: '0x8F3A94725a7686055D1aaBa8a41be506c5dfD079', // msg.sender
  reserve: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984',   // UNI
  amount: '-1',
  interestRateMode: 2
}
```

So it complies with th expected type:
```
export type LPRepayParamsType = {
  user: tEthereumAddress;
  reserve: tEthereumAddress;
  amount: tStringCurrencyUnits;
  interestRateMode: InterestRate;
  onBehalfOf?: tEthereumAddress;
};
```

**Comment by liran319** [comment]
> tEthereumAddress

Thx for reply. 
Yes I see, this is the aave-js repay function payload.
 
I'm using Ether.js contract to call repay, according to docs, the repay function should be passed params like this 
```
function repay(address asset, uint256 amount, uint256 rateMode, address onBehalfOf)
```
And I notice that amount (-1) is transferred to be `constants.MaxUint256.toString()` in aave-js, can I pass `-1` to the contract function ?

**Comment by sendra** [comment]
No, you need to pass max amount to the contract, as its expecting a uint256.

If you are using Ethers.js directly, you could also use the MaxUint256 method to get the max amount

**Comment by liran319** [comment]
> No, you need to pass max amount to the contract, as its expecting a uint256.
> 
> If you are using Ethers.js directly, you could also use the MaxUint256 method to get the max amount

Hi Sendra,

It works, thanks a lot!
